# Mit Skaffold wird Projekt auf Änderungen überwacht und wird automatisch ein neues Container-Image erstellen
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: hasher-carabasa
build:
  artifacts:
    - image: docker.informatik.hs-furtwangen.de/cnc-carabasa/hasher
      jib:
        args:
          - -Dmaven.test.skip=true
deploy:
  # so wird das "helm upgrade" automatisch ausgeführt
  helm:
    releases:
      - name: hasher-carabasa
        chartPath: src/charts/hasher
        artifactOverrides:
          image: docker.informatik.hs-furtwangen.de/cnc-carabasa/hasher