server:
  servlet:
    #Personalisierte URL Pfad damit die Anwendung unter unterschiedliche URL angesprochen werden kann
    context-path: /hasher-carabasa
management:
  # Prometheus Konfiguration damit die Anwendung Metriken genieriert und die über Webserver zur Verfügung stellt
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    tags:
      application: hasher-carabasa
