server:
  servlet:
    context-path: /hasher-carabasa
management:
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    tags:
      application: hasher-carabasa
