#  Manifestdatei für Service
apiVersion: v1
kind: Service
metadata:
  # Service Name
  name: {{ .Values.name }}-{{ .Values.author }}
  #labels für Service um Ressourcen zu kennzeichen
  labels:
    app: {{ .Values.name }}
    author: {{ .Values.author }}
spec:
  # Spezifikationen für Port Weiterleitung
  ports:
    - name: web
      port: 80
      targetPort: 8080
  # So werden zugehörige Pods gefunden und zugewiesen
  selector:
    app: {{ .Values.name }}
    author: {{ .Values.author }}